# Generated by Django 6.0.2 on 2026-02-24 07:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('title', models.CharField(max_length=128, verbose_name='Тақырыбы')),
                ('layout', models.CharField(choices=[('row', 'Қатар (row)'), ('col', 'Баған (col)')], default='row', max_length=10, verbose_name='Көрсету түрі')),
                ('shuffle', models.BooleanField(default=True, verbose_name='Араластыру')),
            ],
            options={
                'verbose_name': 'Сәйкестендіру тапсырма',
                'verbose_name_plural': 'Сәйкестендіру тапсырмалар',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('text', models.TextField(verbose_name='Сұрақ мәтіні')),
                ('question_type', models.CharField(choices=[('single', 'Бір дұрыс жауап'), ('multi', 'Бірнеше дұрыс жауап')], default='single', max_length=10, verbose_name='Сұрақ түрі')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='Ұпай')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
            ],
            options={
                'verbose_name': 'Сұрақ',
                'verbose_name_plural': 'Сұрақтар',
                'ordering': ['test_task_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('attempt_no', models.PositiveIntegerField(default=1, verbose_name='Нәтиже нөмірі')),
                ('status', models.CharField(choices=[('in_progress', 'Орындап жатыр'), ('submitted', 'Жіберілген'), ('cancelled', 'Болдырылмады')], default='in_progress', max_length=20, verbose_name='Күйі')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Басталған уақыты')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Жіберілген уақыты')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Әрекет бойынша балл')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Қосымша мәлімет')),
            ],
            options={
                'verbose_name': 'Тапсыру әрекеті',
                'verbose_name_plural': 'Тапсыру әрекеттері',
                'ordering': ['user_task_id', 'attempt_no'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='accounts/users/avatars', verbose_name='Аватар')),
                ('role', models.CharField(choices=[('learner', 'Білім алушы'), ('tutor', 'Куратор'), ('admin', 'Администратор')], default='learner', max_length=16, verbose_name='Рөлі')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Қолданушы',
                'verbose_name_plural': 'Қолданушылар',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('is_published', models.BooleanField(default=False, verbose_name='Жарияланған ба')),
                ('title', models.CharField(max_length=255, verbose_name='Атауы')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Кілттік сөз')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттамасы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['order'], name='core_catego_order_d10778_idx'), models.Index(fields=['is_published'], name='core_catego_is_publ_6cfdb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('is_published', models.BooleanField(default=False, verbose_name='Жарияланған ба')),
                ('title', models.CharField(max_length=255, verbose_name='Курс атауы')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Кілттік сөз')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Сурет')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттамасы')),
                ('level', models.CharField(choices=[('beginner', 'Бастапқы'), ('intermediate', 'Орта'), ('advanced', 'Жоғары')], default='beginner', max_length=20, verbose_name='Деңгейі')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курстар',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('left_text', models.TextField(verbose_name='Сол жақ мәтін')),
                ('right_text', models.TextField(verbose_name='Оң жақ мәтін')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
                ('matching_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='core.matchingtask', verbose_name='Сәйкестендіру тапсырма')),
            ],
            options={
                'verbose_name': 'Жұп',
                'verbose_name_plural': 'Жұптар',
                'ordering': ['matching_task_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('is_published', models.BooleanField(default=False, verbose_name='Жарияланған ба')),
                ('title', models.CharField(max_length=255, verbose_name='Модуль атауы')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттамасы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модульдер',
                'ordering': ['course_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('is_published', models.BooleanField(default=False, verbose_name='Жарияланған ба')),
                ('title', models.CharField(max_length=255, verbose_name='Сабақ атауы')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттамасы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Ұзақтығы (мин)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Сабақ',
                'verbose_name_plural': 'Сабақтар',
                'ordering': ['module_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('text', models.TextField(verbose_name='Жауап нұсқасы')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс па')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question', verbose_name='Сұрақ')),
            ],
            options={
                'verbose_name': 'Нұсқа',
                'verbose_name_plural': 'Нұсқалар',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('is_published', models.BooleanField(default=False, verbose_name='Жарияланған ба')),
                ('task_type', models.CharField(choices=[('video', 'Видео'), ('reading', 'Оқылым'), ('test', 'Тест'), ('matching', 'Сәйкестендіру')], max_length=20, verbose_name='Тапсырма түрі')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
                ('is_gradable', models.BooleanField(default=True, help_text='Видео/оқылым үшін False, тест/сәйкестендіру үшін True', verbose_name='Бағалана ма')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Тек баға қойылатын тапсырмалар үшін', null=True, verbose_name='Балл (1–10)')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Уақыты (мин)')),
                ('is_required', models.BooleanField(default=True, verbose_name='Міндетті ме')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Тапсырма',
                'verbose_name_plural': 'Тапсырмалар',
                'ordering': ['lesson_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('content', models.TextField(help_text='Қолданушыға көрсетілетін мәтін', verbose_name='Оқу мәтіні')),
                ('task', models.OneToOneField(limit_choices_to={'task_type': 'reading'}, on_delete=django.db.models.deletion.CASCADE, related_name='reading', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Оқу тапсырмасы',
                'verbose_name_plural': 'Оқу тапсырмалары',
            },
        ),
        migrations.AddField(
            model_name='matchingtask',
            name='task',
            field=models.OneToOneField(limit_choices_to={'task_type': 'matching'}, on_delete=django.db.models.deletion.CASCADE, related_name='matching', to='core.task', verbose_name='Тапсырма'),
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('selected_option_ids', models.JSONField(blank=True, default=list, verbose_name='Таңдалған нұсқалар')),
                ('option_order', models.JSONField(blank=True, default=list, verbose_name='Нұсқалар реті (freeze)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс па')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Ұпай')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Жауап берілген уақыты')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.question', verbose_name='Сұрақ')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='core.taskattempt', verbose_name='Әрекет')),
            ],
            options={
                'verbose_name': 'Сұрақ нәтижесі',
                'verbose_name_plural': 'Сұрақ нәтижелері',
            },
        ),
        migrations.CreateModel(
            name='MatchingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('answer', models.JSONField(blank=True, default=dict, verbose_name='Жауап')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс па')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Ұпай')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_attempt', to='core.taskattempt', verbose_name='Әрекет')),
            ],
            options={
                'verbose_name': 'Сәйкестендіру жауабы',
                'verbose_name_plural': 'Сәйкестендіру жауаптары',
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('title', models.CharField(max_length=128, verbose_name='Тақырыбы')),
                ('max_points', models.PositiveSmallIntegerField(default=0, verbose_name='Макс. ұпай')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Сұрақтарды араластыру')),
                ('shuffle_options', models.BooleanField(default=True, verbose_name='Нұсқаларды араластыру')),
                ('task', models.OneToOneField(limit_choices_to={'task_type': 'test'}, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Тест тапсырма',
                'verbose_name_plural': 'Тест тапсырмалар',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.testtask', verbose_name='Тест тапсырма'),
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Басталмаған'), ('in_progress', 'Оқып жатыр'), ('completed', 'Аяқталған')], default='not_started', max_length=20, verbose_name='Күйі')),
                ('progress_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Прогресс (%)')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Пайыз (%)')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Жиынтық балл')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Басталған уақыты')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Аяқталған уақыты')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='core.course', verbose_name='Курс')),
                ('last_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.lesson', verbose_name='Соңғы сабақ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Қолданушы курсы',
                'verbose_name_plural': 'Қолданушы курстары',
            },
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Басталмаған'), ('in_progress', 'Оқып жатыр'), ('completed', 'Аяқталған')], default='not_started', max_length=20, verbose_name='Күйі')),
                ('progress_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Прогресс (%)')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Пайыз (%)')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Жиынтық балл')),
                ('last_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.lesson', verbose_name='Соңғы сабақ')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to='core.module', verbose_name='Модуль')),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to='core.usercourse', verbose_name='Қолданушы курсы')),
            ],
            options={
                'verbose_name': 'Қолданушы модулі',
                'verbose_name_plural': 'Қолданушы модульдері',
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Басталмаған'), ('in_progress', 'Оқып жатыр'), ('completed', 'Аяқталған')], default='not_started', max_length=20, verbose_name='Күйі')),
                ('time_spent_sec', models.PositiveIntegerField(default=0, verbose_name='Жұмсалған уақыт (сек)')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Жиынтық балл')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Пайыз (%)')),
                ('progress_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Прогресс (%)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='core.lesson', verbose_name='Сабақ')),
                ('user_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.usermodule', verbose_name='Қолданушы модулі')),
            ],
            options={
                'verbose_name': 'Қолданушы сабағы',
                'verbose_name_plural': 'Қолданушы сабақтары',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('status', models.CharField(choices=[('not_started', 'Басталмаған'), ('in_progress', 'Орындап жатыр'), ('submitted', 'Жіберілген'), ('graded', 'Бағаланған'), ('completed', 'Аяқталған')], default='not_started', max_length=20, verbose_name='Күйі')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Басталған уақыты')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Жіберілген уақыты')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Бағаланған уақыты')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='Тапсыру саны')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Жинаған балл')),
                ('teacher_feedback', models.TextField(blank=True, verbose_name='Оқытушы пікірі')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='core.task', verbose_name='Тапсырма')),
                ('user_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='core.userlesson', verbose_name='Қолданушы сабағы')),
            ],
            options={
                'verbose_name': 'Қолданушы тапсырмасы',
                'verbose_name_plural': 'Қолданушы тапсырмалары',
            },
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='user_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.usertask', verbose_name='Қолданушы тапсырмасы'),
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('watched_sec', models.PositiveIntegerField(default=0, verbose_name='Қараған уақыты (сек)')),
                ('last_position_sec', models.PositiveIntegerField(default=0, verbose_name='Соңғы позиция (сек)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Аяқталды ма')),
                ('user_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='core.usertask', verbose_name='Қолданушы тапсырмасы')),
            ],
            options={
                'verbose_name': 'Видео прогресс',
                'verbose_name_plural': 'Видео прогрестер',
            },
        ),
        migrations.CreateModel(
            name='VideoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('url', models.TextField(verbose_name='Видео сілтемесі')),
                ('min_watch_sec', models.PositiveIntegerField(default=0, verbose_name='Минимум қарау уақыты (сек)')),
                ('allow_skip', models.BooleanField(default=True, verbose_name='Өткізіп жіберуге бола ма')),
                ('task', models.OneToOneField(limit_choices_to={'task_type': 'video'}, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Видео тапсырма',
                'verbose_name_plural': 'Видео тапсырмалар',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'order'], name='core_course_categor_ebd07d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published'], name='core_course_is_publ_efb2a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchingpair',
            constraint=models.UniqueConstraint(fields=('matching_task', 'order'), name='uniq_pair_order_in_matching'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='core_module_course__d6848a_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_published'], name='core_module_is_publ_886bbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='uniq_module_order_in_course'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='core_lesson_module__bc71c5_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_published'], name='core_lesson_is_publ_a09358_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='uniq_lesson_order_in_module'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['lesson', 'order'], name='core_task_lesson__f7aa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type'], name='core_task_task_ty_c0c7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_published'], name='core_task_is_publ_7157ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='uniq_task_order_in_lesson'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task_type__in', ['video', 'reading']), ('is_gradable', False), ('rating__isnull', True)), models.Q(('task_type__in', ['test', 'matching']), ('is_gradable', True), ('rating__gte', 1), ('rating__lte', 10)), _connector='OR'), name='chk_task_grading_rules'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['attempt', 'question'], name='core_questi_attempt_bb0b53_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test_task', 'order'], name='core_questi_test_ta_d0e5b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('test_task', 'order'), name='uniq_question_order_in_test_task'),
        ),
        migrations.AddConstraint(
            model_name='usercourse',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='uniq_user_course'),
        ),
        migrations.AddConstraint(
            model_name='usermodule',
            constraint=models.UniqueConstraint(fields=('user_course', 'module'), name='uniq_user_module'),
        ),
        migrations.AddConstraint(
            model_name='userlesson',
            constraint=models.UniqueConstraint(fields=('user_module', 'lesson'), name='uniq_user_lesson'),
        ),
        migrations.AddConstraint(
            model_name='usertask',
            constraint=models.UniqueConstraint(fields=('user_lesson', 'task'), name='uniq_user_task'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['user_task', 'status'], name='core_taskat_user_ta_a1efb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskattempt',
            constraint=models.UniqueConstraint(fields=('user_task', 'attempt_no'), name='uniq_attempt_no_per_user_task'),
        ),
    ]
