# Generated by Django 5.2.3 on 2026-02-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Ашық курс'),
        ),
    ]
