# Generated by Django 6.0.2 on 2026-02-23 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('is_published', models.BooleanField(default=False, verbose_name='Жарияланған ба')),
                ('title', models.CharField(max_length=255, verbose_name='Атауы')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Кілттік сөз')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттамасы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['order'], name='core_catego_order_d10778_idx'), models.Index(fields=['is_published'], name='core_catego_is_publ_6cfdb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('is_published', models.BooleanField(default=False, verbose_name='Жарияланған ба')),
                ('title', models.CharField(max_length=255, verbose_name='Курс атауы')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Кілттік сөз')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Сурет')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттамасы')),
                ('level', models.CharField(choices=[('beginner', 'Бастапқы'), ('intermediate', 'Орта'), ('advanced', 'Жоғары')], default='beginner', max_length=20, verbose_name='Деңгейі')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курстар',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('is_published', models.BooleanField(default=False, verbose_name='Жарияланған ба')),
                ('title', models.CharField(max_length=255, verbose_name='Модуль атауы')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттамасы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модульдер',
                'ordering': ['course_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('is_published', models.BooleanField(default=False, verbose_name='Жарияланған ба')),
                ('title', models.CharField(max_length=255, verbose_name='Сабақ атауы')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттамасы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
                ('duration_sec', models.PositiveIntegerField(default=0, verbose_name='Ұзақтығы (сек)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Сабақ',
                'verbose_name_plural': 'Сабақтар',
                'ordering': ['module_id', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'order'], name='core_course_categor_ebd07d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published'], name='core_course_is_publ_efb2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='core_module_course__d6848a_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_published'], name='core_module_is_publ_886bbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='uniq_module_order_in_course'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='core_lesson_module__bc71c5_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_published'], name='core_lesson_is_publ_a09358_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='uniq_lesson_order_in_module'),
        ),
    ]
