# Generated by Django 5.2.3 on 2025-08-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері'),
        ),
    ]
