# Generated by Django 6.0.2 on 2026-02-23 11:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_course_module_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('text', models.TextField(verbose_name='Сұрақ мәтіні')),
                ('question_type', models.CharField(choices=[('single', 'Бір дұрыс жауап'), ('multi', 'Бірнеше дұрыс жауап')], default='single', max_length=10, verbose_name='Сұрақ түрі')),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='Ұпай')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
            ],
            options={
                'verbose_name': 'Сұрақ',
                'verbose_name_plural': 'Сұрақтар',
                'ordering': ['test_task_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('text', models.TextField(verbose_name='Жауап нұсқасы')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс па')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question', verbose_name='Сұрақ')),
            ],
            options={
                'verbose_name': 'Нұсқа',
                'verbose_name_plural': 'Нұсқалар',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('is_published', models.BooleanField(default=False, verbose_name='Жарияланған ба')),
                ('title', models.CharField(max_length=255, verbose_name='Тапсырма атауы')),
                ('task_type', models.CharField(choices=[('video', 'Видео'), ('reading', 'Оқылым'), ('test', 'Тест'), ('matching', 'Сәйкестендіру')], max_length=20, verbose_name='Тапсырма түрі')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Балл (1–10)')),
                ('duration_sec', models.PositiveIntegerField(default=0, verbose_name='Уақыт шектеуі (сек)')),
                ('is_required', models.BooleanField(default=True, verbose_name='Міндетті ме')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Параметрлер')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Тапсырма',
                'verbose_name_plural': 'Тапсырмалар',
                'ordering': ['lesson_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Қолданушыға көрсетілетін мәтін', verbose_name='Оқу мәтіні')),
                ('task', models.OneToOneField(limit_choices_to={'task_type': 'reading'}, on_delete=django.db.models.deletion.CASCADE, related_name='reading', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Оқу тапсырмасы',
                'verbose_name_plural': 'Оқу тапсырмалары',
            },
        ),
        migrations.CreateModel(
            name='MatchingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('layout', models.CharField(choices=[('row', 'Қатар (row)'), ('col', 'Баған (col)')], default='row', max_length=10, verbose_name='Көрсету түрі')),
                ('shuffle', models.BooleanField(default=True, verbose_name='Араластыру')),
                ('task', models.OneToOneField(limit_choices_to={'task_type': 'matching'}, on_delete=django.db.models.deletion.CASCADE, related_name='matching', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Сәйкестендіру тапсырма',
                'verbose_name_plural': 'Сәйкестендіру тапсырмалар',
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Сұрақтарды араластыру')),
                ('shuffle_options', models.BooleanField(default=True, verbose_name='Нұсқаларды араластыру')),
                ('task', models.OneToOneField(limit_choices_to={'task_type': 'test'}, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Тест тапсырма',
                'verbose_name_plural': 'Тест тапсырмалар',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.testtask', verbose_name='Тест тапсырма'),
        ),
        migrations.CreateModel(
            name='VideoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('url', models.TextField(verbose_name='Видео сілтемесі')),
                ('min_watch_sec', models.PositiveIntegerField(default=0, verbose_name='Минимум қарау уақыты (сек)')),
                ('allow_skip', models.BooleanField(default=True, verbose_name='Өткізіп жіберуге бола ма')),
                ('task', models.OneToOneField(limit_choices_to={'task_type': 'video'}, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Видео тапсырма',
                'verbose_name_plural': 'Видео тапсырмалар',
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('left_text', models.CharField(max_length=255, verbose_name='Сол жақ мәтін')),
                ('right_text', models.CharField(max_length=255, verbose_name='Оң жақ мәтін')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
                ('matching_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='core.matchingtask', verbose_name='Сәйкестендіру тапсырма')),
            ],
            options={
                'verbose_name': 'Жұп',
                'verbose_name_plural': 'Жұптар',
                'ordering': ['matching_task_id', 'order'],
                'constraints': [models.UniqueConstraint(fields=('matching_task', 'order'), name='uniq_pair_order_in_matching')],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['lesson', 'order'], name='core_task_lesson__f7aa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type'], name='core_task_task_ty_c0c7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_published'], name='core_task_is_publ_7157ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='uniq_task_order_in_lesson'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 10)), name='chk_task_rating_1_10'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test_task', 'order'], name='core_questi_test_ta_d0e5b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('test_task', 'order'), name='uniq_question_order_in_test_task'),
        ),
    ]
