# Generated by Django 5.2.3 on 2026-02-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='owner',
        ),
    ]
