# Generated by Django 5.2.3 on 2025-08-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_chapter_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_score',
        ),
    ]
