# Generated by Django 6.0.2 on 2026-02-23 12:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_option_task_readingtask_matchingtask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('attempt_no', models.PositiveIntegerField(default=1, verbose_name='Нәтиже нөмірі')),
                ('status', models.CharField(choices=[('in_progress', 'Орындап жатыр'), ('submitted', 'Жіберілген'), ('cancelled', 'Болдырылмады')], default='in_progress', max_length=20, verbose_name='Күйі')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Басталған уақыты')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Жіберілген уақыты')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Әрекет бойынша балл')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Қосымша мәлімет')),
            ],
            options={
                'verbose_name': 'Тапсыру әрекеті',
                'verbose_name_plural': 'Тапсыру әрекеттері',
                'ordering': ['user_task_id', 'attempt_no'],
            },
        ),
        migrations.CreateModel(
            name='MatchingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('answer', models.JSONField(blank=True, default=dict, verbose_name='Жауап')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс па')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Ұпай')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_attempt', to='core.taskattempt', verbose_name='Әрекет')),
            ],
            options={
                'verbose_name': 'Сәйкестендіру әрекеті',
                'verbose_name_plural': 'Сәйкестендіру әрекеттері',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('status', models.CharField(choices=[('not_started', 'Басталмаған'), ('in_progress', 'Орындап жатыр'), ('submitted', 'Жіберілген'), ('graded', 'Бағаланған'), ('completed', 'Аяқталған')], default='not_started', max_length=20, verbose_name='Күйі')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Басталған уақыты')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Жіберілген уақыты')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Бағаланған уақыты')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='Тапсыру саны')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Жинаған балл')),
                ('teacher_feedback', models.TextField(blank=True, verbose_name='Оқытушы пікірі')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='core.task', verbose_name='Тапсырма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Қолданушы тапсырмасы',
                'verbose_name_plural': 'Қолданушы тапсырмалары',
            },
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='user_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.usertask', verbose_name='Қолданушы тапсырмасы'),
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('watched_sec', models.PositiveIntegerField(default=0, verbose_name='Қараған уақыты (сек)')),
                ('last_position_sec', models.PositiveIntegerField(default=0, verbose_name='Соңғы позиция (сек)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Аяқталды ма')),
                ('user_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='core.usertask', verbose_name='Қолданушы тапсырмасы')),
            ],
            options={
                'verbose_name': 'Видео прогресс',
                'verbose_name_plural': 'Видео прогрестер',
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('selected_option_ids', models.JSONField(blank=True, default=list, verbose_name='Таңдалған нұсқалар')),
                ('option_order', models.JSONField(blank=True, default=list, verbose_name='Нұсқалар реті (freeze)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс па')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Ұпай')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Жауап берілген уақыты')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.question', verbose_name='Сұрақ')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='core.taskattempt', verbose_name='Әрекет')),
            ],
            options={
                'verbose_name': 'Сұрақ әрекеті',
                'verbose_name_plural': 'Сұрақ әрекеттері',
                'indexes': [models.Index(fields=['attempt', 'question'], name='core_questi_attempt_bb0b53_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('status', models.CharField(choices=[('not_started', 'Басталмаған'), ('in_progress', 'Оқып жатыр'), ('completed', 'Аяқталған')], default='not_started', max_length=20, verbose_name='Күйі')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Басталған уақыты')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Аяқталған уақыты')),
                ('time_spent_sec', models.PositiveIntegerField(default=0, verbose_name='Жұмсалған уақыт (сек)')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Жиынтық балл')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Пайыз (%)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='core.lesson', verbose_name='Сабақ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Қолданушы сабағы',
                'verbose_name_plural': 'Қолданушы сабақтары',
                'indexes': [models.Index(fields=['user', 'status'], name='core_userle_user_id_c56cdf_idx'), models.Index(fields=['lesson', 'status'], name='core_userle_lesson__c1ca65_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='uniq_user_lesson'), models.CheckConstraint(condition=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='chk_user_lesson_percent_0_100')],
            },
        ),
        migrations.AddIndex(
            model_name='usertask',
            index=models.Index(fields=['user', 'status'], name='core_userta_user_id_e5627a_idx'),
        ),
        migrations.AddIndex(
            model_name='usertask',
            index=models.Index(fields=['task', 'status'], name='core_userta_task_id_961560_idx'),
        ),
        migrations.AddConstraint(
            model_name='usertask',
            constraint=models.UniqueConstraint(fields=('user', 'task'), name='uniq_user_task'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['user_task', 'status'], name='core_taskat_user_ta_a1efb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskattempt',
            constraint=models.UniqueConstraint(fields=('user_task', 'attempt_no'), name='uniq_attempt_no_per_user_task'),
        ),
    ]
