# Generated by Django 5.2.3 on 2026-02-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chapter_subject_alter_lesson_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessondocs',
            name='description',
        ),
    ]
