# Generated by Django 5.2.3 on 2025-08-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_question_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='content',
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='user_lesson',
        ),
        migrations.RemoveField(
            model_name='uservideo',
            name='user_content',
        ),
        migrations.RemoveField(
            model_name='uservideo',
            name='video',
        ),
        migrations.AlterField(
            model_name='usermatching',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Сәйкес пе?'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='UserContent',
        ),
        migrations.DeleteModel(
            name='UserVideo',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
