# Generated by Django 6.0.2 on 2026-02-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_taskattempt_matchingattempt_usertask_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchingattempt',
            options={'verbose_name': 'Сәйкестендіру жауабы', 'verbose_name_plural': 'Сәйкестендіру жауаптары'},
        ),
        migrations.AlterModelOptions(
            name='questionattempt',
            options={'verbose_name': 'Сұрақ нәтижесі', 'verbose_name_plural': 'Сұрақ нәтижелері'},
        ),
    ]
