# Generated by Django 5.2.3 on 2026-02-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_lessondocs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('video', 'Видеосабақ'), ('reading', 'Оқу мәтіні'), ('test', 'Тест'), ('matching', 'Сәйкестендіру')], default='video', max_length=32, verbose_name='Тапсырма түрі'),
        ),
    ]
