# Generated by Django 6.0.2 on 2026-02-23 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_matchingattempt_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='chk_task_rating_1_10',
        ),
        migrations.AddField(
            model_name='readingtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Жасалған уақыты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_gradable',
            field=models.BooleanField(default=True, help_text='Видео/оқылым үшін False, тест/сәйкестендіру үшін True', verbose_name='Бағалана ма'),
        ),
        migrations.AlterField(
            model_name='task',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Тек баға қойылатын тапсырмалар үшін', null=True, verbose_name='Балл (1–10)'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task_type__in', ['video', 'reading']), ('is_gradable', False), ('rating__isnull', True)), models.Q(('task_type__in', ['test', 'matching']), ('is_gradable', True), ('rating__gte', 1), ('rating__lte', 10)), _connector='OR'), name='chk_task_grading_rules'),
        ),
    ]
