# Generated by Django 5.2.3 on 2025-08-07 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_video_content_remove_usercontent_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL сілтеме')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Видео уақыт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.task', verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Видеосабақ',
                'verbose_name_plural': 'Видеосабақтар',
                'ordering': ('order',),
            },
        ),
    ]
