# Generated by Django 5.2.3 on 2026-02-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_task_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='title',
        ),
    ]
