# Generated by Django 5.2.3 on 2025-08-07 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='matching',
        ),
        migrations.RemoveField(
            model_name='test',
            name='task',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.AlterModelOptions(
            name='pair',
            options={'verbose_name': 'Сәйкестендіру', 'verbose_name_plural': 'Сәйкестендірулер'},
        ),
        migrations.AlterModelOptions(
            name='textgap',
            options={'verbose_name': 'Сөйлемді аяқтау', 'verbose_name_plural': 'Сөйлемді аяқтау тапсырмалары'},
        ),
        migrations.AlterModelOptions(
            name='usertask',
            options={'verbose_name': 'Қолданушының тапсырмасы', 'verbose_name_plural': 'Қолданушының тапсырмалары'},
        ),
        migrations.AlterModelOptions(
            name='usertextgap',
            options={'verbose_name': 'Қолданушының сәйкестендіруі', 'verbose_name_plural': 'Сөйлемді аяқтау жауаптары'},
        ),
        migrations.AddField(
            model_name='pair',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='core.task', verbose_name='Тапсырма'),
        ),
        migrations.AddField(
            model_name='question',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.task', verbose_name='Тапсырма'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='right_item',
            field=models.CharField(max_length=255, verbose_name='Оң жақ'),
        ),
        migrations.AlterField(
            model_name='usertextgap',
            name='answer',
            field=models.CharField(max_length=255, verbose_name='Жауабы'),
        ),
        migrations.AlterField(
            model_name='usertextgap',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Дұрыс па?'),
        ),
        migrations.AlterField(
            model_name='usertextgap',
            name='user_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_gap_answers', to='core.usertask', verbose_name='Қолданушының тапсырмасы'),
        ),
        migrations.AlterField(
            model_name='userwritten',
            name='answer',
            field=models.TextField(verbose_name='Жауабы'),
        ),
        migrations.AlterField(
            model_name='userwritten',
            name='user_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_written', to='core.usertask', verbose_name='Қолданушының тапсырмасы'),
        ),
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.PositiveIntegerField(default=0, verbose_name='Қараған уақыт (сек)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Аяқталған')),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_videos', to='core.usertask', verbose_name='Қолданушының тапсырмасы')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_videos', to='core.video', verbose_name='Видеосабақ')),
            ],
            options={
                'verbose_name': 'Қолданушының видеосабағы',
                'verbose_name_plural': 'Қолданушының видеосабақтары',
            },
        ),
        migrations.DeleteModel(
            name='Matching',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
