# Generated by Django 5.2.3 on 2026-02-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_reading_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Анықтамасы'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='content',
            field=models.TextField(verbose_name='Мәтін'),
        ),
    ]
