# Generated by Django 5.2.3 on 2025-08-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_pair_matching_remove_test_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Жауап', 'verbose_name_plural': 'Жауаптар'},
        ),
        migrations.AlterModelOptions(
            name='textgap',
            options={'verbose_name': 'Толықтыру', 'verbose_name_plural': 'Толықтырулар'},
        ),
        migrations.AlterModelOptions(
            name='written',
            options={'verbose_name': 'Жазбаша', 'verbose_name_plural': 'Жазбашалар'},
        ),
        migrations.AlterField(
            model_name='option',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('video', 'Видеосабақ'), ('written', 'Жазбаша'), ('text_gap', 'Сөйлемді аяқтау'), ('test', 'Тест'), ('matching', 'Сәйкестендіру')], default='written', max_length=32, verbose_name='Тапсырма түрі'),
        ),
    ]
