# Generated by Django 5.2.3 on 2026-02-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_description_alter_reading_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreading',
            name='reading',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_reading', to='core.reading', verbose_name='Оқу мәтіні'),
            preserve_default=False,
        ),
    ]
