# Generated by Django 5.2.3 on 2025-08-07 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_option_options_alter_textgap_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='user_question',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_options', to='core.option', verbose_name='Жауап'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_options', to='core.usertask', verbose_name='Қолданушы тапсырмасы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('video', 'Видеосабақ'), ('written', 'Жазбаша'), ('text_gap', 'Толықтыру'), ('test', 'Тест'), ('matching', 'Сәйкестендіру')], default='written', max_length=32, verbose_name='Тапсырма түрі'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='options',
            field=models.ManyToManyField(related_name='user_answers', to='core.option', verbose_name='Таңдалған жауаптар'),
        ),
        migrations.DeleteModel(
            name='UserQuestion',
        ),
    ]
