# Generated by Django 5.2.3 on 2025-08-07 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_useranswer_user_question_useranswer_option_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertextgap',
            options={'verbose_name': 'Қолданушының сәйкестендіруі', 'verbose_name_plural': 'Қолданушының сәйкестендірулері'},
        ),
        migrations.AlterModelOptions(
            name='userwritten',
            options={'verbose_name': 'Қолданушының жазбаша жауабы', 'verbose_name_plural': 'Қолданушының жазбаша жауаптары'},
        ),
        migrations.AddField(
            model_name='usertextgap',
            name='text_gap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_text_gaps', to='core.textgap', verbose_name='Cәйкестендіру'),
        ),
        migrations.AddField(
            model_name='userwritten',
            name='written',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_written', to='core.written', verbose_name='Жазбаша'),
        ),
        migrations.AlterField(
            model_name='usertextgap',
            name='user_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_text_gaps', to='core.usertask', verbose_name='Қолданушының тапсырмасы'),
        ),
    ]
