# Generated by Django 5.2.3 on 2026-02-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userreading_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to='core.subject', verbose_name='Курс'),
        ),
    ]
