# Generated by Django 5.2.3 on 2025-08-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usertextgap_options_alter_userwritten_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('video', 'Видеосабақ'), ('written', 'Жазбаша'), ('text_gap', 'Толықтыру'), ('test', 'Тест'), ('matching', 'Сәйкестендіру')], default='video', max_length=32, verbose_name='Тапсырма түрі'),
        ),
    ]
