# Generated by Django 5.2.3 on 2026-02-26 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usersubject_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('description', models.TextField(blank=True, default='', verbose_name='Сипаттамасы')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='books/posters/', verbose_name='Мұқабасы')),
                ('file', models.FileField(upload_to='books/pdf/', verbose_name='Файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Жарияланған')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кітап',
                'verbose_name_plural': 'Кітаптар',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_saved', models.BooleanField(default=True, verbose_name='Сақталды')),
                ('last_page', models.PositiveIntegerField(default=1, verbose_name='Соңғы оқылған бет')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Сақталған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өзгертілген уақыты')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='core.book', verbose_name='Кітап')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Қолданушы кітабы',
                'verbose_name_plural': 'Қолданушы кітаптары',
                'ordering': ['-updated_at', '-id'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
