# Generated by Django 5.2.3 on 2025-08-13 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertextgap',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Жауабы'),
        ),
        migrations.AlterField(
            model_name='usertextgap',
            name='text_gap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_text_gaps', to='core.textgap', verbose_name='Толықтыру'),
        ),
    ]
