# Generated by Django 5.2.3 on 2026-02-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_book_userbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('slug', models.SlugField(max_length=255, verbose_name='Кіллтік сөзі')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Симулятор',
                'verbose_name_plural': 'Симуляторлар',
            },
        ),
    ]
