# Generated by Django 5.2.3 on 2025-08-13 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_usertextgap_answer_alter_usertextgap_text_gap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='option',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_options', to='core.question', verbose_name='Жауап'),
        ),
    ]
