# Generated by Django 5.2.3 on 2026-02-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_simulator'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Реті'),
        ),
    ]
