# Generated by Django 5.2.3 on 2025-08-13 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_useranswer_option_useranswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertextgap',
            name='user_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_text_gaps', to='core.usertask', verbose_name='Қолданушының тапсырмасы'),
        ),
        migrations.AlterField(
            model_name='userwritten',
            name='user_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_written', to='core.usertask', verbose_name='Қолданушының тапсырмасы'),
        ),
    ]
