# Generated by Django 5.2.3 on 2026-04-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_simulator_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('slug', models.SlugField(max_length=255, verbose_name='Кіллтік сөзі')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Реті')),
            ],
            options={
                'verbose_name': 'Жоба',
                'verbose_name_plural': 'Жобалар',
            },
        ),
    ]
