# Generated by Django 5.2.3 on 2025-08-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_usertextgap_user_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlesson',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Басталған уақыты'),
        ),
    ]
