# Generated by Django 5.2.3 on 2025-08-13 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userlesson_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Басталған уақыты'),
            preserve_default=False,
        ),
    ]
