# Generated by Django 5.2.3 on 2025-08-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_userlesson_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchapter',
            name='chapter_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Бөлімнің жалпы бағасы'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='lesson_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сабақтың бағасы'),
        ),
        migrations.AlterField(
            model_name='usersubject',
            name='subject_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Пәннің жалпы бағасы'),
        ),
    ]
