# Generated by Django 5.2.3 on 2025-08-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_userchapter_chapter_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwritten',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Жіберілді'),
        ),
    ]
