# Generated by Django 5.2.3 on 2025-08-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermatching',
            name='pair',
        ),
        migrations.RemoveField(
            model_name='usermatching',
            name='user_task',
        ),
        migrations.DeleteModel(
            name='Pair',
        ),
        migrations.DeleteModel(
            name='UserMatching',
        ),
    ]
