# Generated by Django 5.2.3 on 2025-08-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_usermatching_pair_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order',), 'verbose_name': 'Тест сұрағы', 'verbose_name_plural': 'Тест сұрақтары'},
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='status',
            field=models.CharField(choices=[('no-started', 'Сабақ басталмады'), ('in-progress', 'Сабақ өтілуде'), ('finished', 'Сабақ аяқталды')], default='no-started', max_length=64, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL сілтеме'),
        ),
    ]
