# Generated by Django 5.2.3 on 2025-08-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_question_options_alter_userlesson_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.TextField(verbose_name='URL сілтеме'),
        ),
    ]
