# Generated by Django 5.2.3 on 2025-08-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwritten',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='core/models/user_written/files/', verbose_name='Файл'),
        ),
    ]
