# Generated by Django 5.2.3 on 2025-08-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_userwritten_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchapter',
            old_name='chapter_score',
            new_name='chapter_rating',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_score',
        ),
        migrations.RemoveField(
            model_name='usersubject',
            name='subject_score',
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сабақтың уақыты (мин)'),
        ),
        migrations.AddField(
            model_name='task',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Жалпы бағасы'),
        ),
        migrations.AddField(
            model_name='usersubject',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Пайыздық мөлшері'),
        ),
        migrations.AddField(
            model_name='usersubject',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Жалпы бағасы'),
        ),
    ]
