# Generated by Django 5.2.3 on 2025-08-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_chapter_score_userchapter_chapter_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
    ]
