# Generated by Django 5.2.3 on 2025-08-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_video_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchapter',
            name='chapter_rating',
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='lesson_score',
        ),
        migrations.AddField(
            model_name='userchapter',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Пайыздық мөлшері'),
        ),
        migrations.AddField(
            model_name='userchapter',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Жалпы бағасы'),
        ),
        migrations.AddField(
            model_name='userlesson',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Пайыздық мөлшері'),
        ),
        migrations.AddField(
            model_name='userlesson',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Жалпы бағасы'),
        ),
        migrations.AlterField(
            model_name='usersubject',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Пайыздық мөлшері'),
        ),
    ]
