# Generated by Django 5.2.3 on 2025-08-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_userchapter_chapter_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='score',
        ),
        migrations.AddField(
            model_name='usertask',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Пайыздық мөлшері'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Жалпы бағасы'),
        ),
    ]
