# Generated by Django 5.2.3 on 2025-08-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_usertask_score_usertask_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Тапсырма уақыты (мин)'),
        ),
    ]
