# Generated by Django 5.2.3 on 2025-08-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_lesson_duration_alter_task_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='percentage',
        ),
    ]
