# Generated by Django 5.2.3 on 2025-08-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_usertask_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Басталған уақыты'),
        ),
    ]
