# Generated by Django 5.2.3 on 2025-08-21 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_userlesson_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Атауы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілігі')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Сәйкес баған',
                'verbose_name_plural': 'Сәйкес бағандар',
            },
        ),
        migrations.CreateModel(
            name='MatchingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Жауабы')),
                ('correct_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_items', to='core.matchingcolumn', verbose_name='Тапсырма')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Сәйкес элемент',
                'verbose_name_plural': 'Сәйкес элементтер',
            },
        ),
        migrations.CreateModel(
            name='UserMatchingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс жауап')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matchingitem', verbose_name='Жауап')),
                ('selected_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matchingcolumn', verbose_name='Баған')),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.usertask', verbose_name='Қолданушының тапсырмасы')),
            ],
        ),
    ]
