# Generated by Django 5.2.3 on 2025-08-21 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_matchingcolumn_matchingitem_usermatchinganswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingitem',
            name='task',
        ),
    ]
