# Generated by Django 5.2.3 on 2025-08-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_matchingitem_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingitem',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Жауабы'),
        ),
    ]
