# Generated by Django 5.2.3 on 2025-08-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_matchingitem_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermatchinganswer',
            options={'verbose_name': 'Қолданушының сәйкестендіруі', 'verbose_name_plural': 'Қолданушының сәйкестендірулері'},
        ),
    ]
