# Generated by Django 5.2.3 on 2025-08-21 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_usermatchinganswer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermatchinganswer',
            name='selected_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.matchingcolumn', verbose_name='Баған'),
        ),
    ]
