# Generated by Django 5.2.3 on 2025-08-21 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_usermatchinganswer_selected_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermatchinganswer',
            name='user_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_answers', to='core.usertask', verbose_name='Қолданушының тапсырмасы'),
        ),
    ]
