# Generated by Django 5.2.3 on 2025-08-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_usermatchinganswer_user_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('lesson', 'Сабақ'), ('chapter', 'Бөлім'), ('quarter', 'Тоқсан')], default='lesson', max_length=32, verbose_name='Сабақ түрі'),
        ),
    ]
