# Generated by Django 5.2.3 on 2025-08-26 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='params',
            field=models.CharField(choices=[('none', 'Таңдалмаған'), ('Тест', [('quiz', 'Тест'), ('true-false', 'Ақиқат/жалған')]), ('Сәйкестендіру', [('row', 'Қатар'), ('col', 'Баған')])], default='none', max_length=32, verbose_name='Параметрлер'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('video', 'Видеосабақ'), ('written', 'Жазбаша'), ('text_gap', 'Толықтыру'), ('test', 'Тест'), ('matching', 'Сәйкестендіру'), ('table', 'Кесте толтыру')], default='video', max_length=32, verbose_name='Тапсырма түрі'),
        ),
        migrations.CreateModel(
            name='TableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Баған атауы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_columns', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Кесте бағаны',
                'verbose_name_plural': 'Кесте бағандары',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Қатар атауы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_rows', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Кесте қатары',
                'verbose_name_plural': 'Кесте қатарлары',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дұрыс жауап')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='core.tablecolumn', verbose_name='Баған')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='core.tablerow', verbose_name='Қатар')),
            ],
            options={
                'verbose_name': 'Ұяшық',
                'verbose_name_plural': 'Ұяшықтар',
                'unique_together': {('row', 'column')},
            },
        ),
    ]
