# Generated by Django 5.2.3 on 2025-08-26 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_task_params_alter_task_task_type_tablecolumn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTableAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=255, null=True, verbose_name='Қолданушы жауабы')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс па?')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='core.tablecolumn', verbose_name='Баған')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='core.tablerow', verbose_name='Қатар')),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_table_answers', to='core.usertask', verbose_name='Қолданушы тапсырмасы')),
            ],
            options={
                'verbose_name': 'Кесте ұяшығына жауап',
                'verbose_name_plural': 'Кесте ұяшығына жауаптар',
                'unique_together': {('user_task', 'row', 'column')},
            },
        ),
    ]
