# Generated by Django 5.2.3 on 2025-08-26 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_usertableanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertableanswer',
            name='is_correct',
        ),
        migrations.DeleteModel(
            name='TableCell',
        ),
    ]
