# Generated by Django 5.2.3 on 2025-08-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_usertableanswer_is_correct_delete_tablecell'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertableanswer',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Жіберілді'),
        ),
    ]
