# Generated by Django 5.2.3 on 2025-08-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_usertableanswer_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingcolumn',
            name='label',
            field=models.TextField(verbose_name='Атауы'),
        ),
    ]
