# Generated by Django 5.2.3 on 2025-09-02 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_matchingcolumn_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Өте нашар'), (2, 'Нашар'), (3, 'Орташа'), (4, 'Жақсы'), (5, 'Тамаша')], verbose_name='Бағасы')),
                ('comment', models.TextField(blank=True, verbose_name='Пікір')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жазылған уақыты')),
                ('user_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.userlesson', verbose_name='Қолданушының сабағы')),
            ],
            options={
                'verbose_name': 'Кері байланыс',
                'verbose_name_plural': 'Кері байланыстар',
            },
        ),
    ]
