# Generated by Django 5.2.3 on 2025-09-04 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False, verbose_name='Дұрыс жауап')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_cells', to='core.tablecolumn', verbose_name='Баған')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_cells', to='core.tablerow', verbose_name='Қатар')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_cells', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Кесте ұяшығы (дұрыс жауап)',
                'verbose_name_plural': 'Кесте ұяшықтары (дұрыс жауаптар)',
                'unique_together': {('task', 'row', 'column')},
            },
        ),
    ]
