# Generated by Django 5.2.3 on 2025-09-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_tablecell'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_class',
            field=models.CharField(choices=[('none', 'Сыныпты таңдау'), ('8b', '8Б сынып'), ('8v', '8В сынып')], default='none', max_length=32, verbose_name='Сыныбы'),
        ),
    ]
