# Generated by Django 5.2.3 on 2025-09-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_user_user_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecolumn',
            name='label',
            field=models.TextField(verbose_name='Баған атауы'),
        ),
        migrations.AlterField(
            model_name='tablerow',
            name='label',
            field=models.TextField(verbose_name='Қатар атауы'),
        ),
    ]
