# Generated by Django 5.2.3 on 2025-09-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_tablecolumn_label_alter_tablerow_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tablecell',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tablecell',
            name='task',
        ),
    ]
