# Generated by Django 5.2.3 on 2025-09-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_tablecell_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertableanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='usertableanswer',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Белгіленген'),
        ),
    ]
