# Generated by Django 5.2.3 on 2025-09-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_usertableanswer_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertableanswer',
            name='is_submitted',
        ),
    ]
