# Generated by Django 5.2.3 on 2025-09-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_usertableanswer_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lab_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Виртуалды лаборатория'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Соңғы жаңарту'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Мұғалім'), ('admin', 'Администрация')], default='student', max_length=32, verbose_name='Қолданушы типі'),
        ),
    ]
