# Generated by Django 5.2.3 on 2025-09-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_lesson_lab_link_alter_lesson_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='params',
            field=models.CharField(choices=[('none', 'Таңдалмаған'), ('Тест', [('quiz', 'Тест'), ('true-false', 'Ақиқат/жалған')]), ('Сәйкестендіру', [('row', 'Қатар'), ('col', 'Баған')]), ('lab', 'Виртуалды лаборатория')], default='none', max_length=32, verbose_name='Параметрлер'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('video', 'Видеосабақ'), ('written', 'Жазбаша'), ('test', 'Тест'), ('matching', 'Сәйкестендіру')], default='video', max_length=32, verbose_name='Тапсырма түрі'),
        ),
    ]
