# Generated by Django 5.2.3 on 2025-09-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_user_user_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Оқытушы'), ('admin', 'Администрация')], default='student', max_length=32, verbose_name='Қолданушы типі'),
        ),
    ]
