# Generated by Django 5.2.3 on 2025-09-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.CharField(choices=[('none', 'Топты таңдау'), ('8b', '1-топ'), ('8v', '2-топ')], default='none', max_length=32, verbose_name='Сыныбы'),
        ),
    ]
