# Generated by Django 5.2.3 on 2025-09-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_user_user_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_type',
        ),
    ]
