# Generated by Django 5.2.3 on 2026-02-25 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_lesson_lesson_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_class',
        ),
    ]
