# Generated by Django 5.2.3 on 2026-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_user_user_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('created_at',), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курстар'},
        ),
        migrations.AlterField(
            model_name='task',
            name='params',
            field=models.CharField(choices=[('none', 'Таңдалмаған'), ('Тест', [('quiz', 'Тест'), ('true-false', 'Ақиқат/жалған')]), ('Сәйкестендіру', [('row', 'Қатар'), ('col', 'Баған')])], default='none', max_length=32, verbose_name='Параметрлер'),
        ),
    ]
