# Generated by Django 5.2.3 on 2026-02-25 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_subject_options_alter_task_params'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchapter',
            options={'verbose_name': 'Қолданушының курс бөлімі', 'verbose_name_plural': 'Қолданушының курс бөлімдері'},
        ),
        migrations.AlterModelOptions(
            name='usersubject',
            options={'verbose_name': 'Қолданушының курсы', 'verbose_name_plural': 'Қолданушының курстары'},
        ),
        migrations.AlterField(
            model_name='userchapter',
            name='user_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chapters', to='core.usersubject', verbose_name='Қолданушының курсы'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='user_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='core.usersubject', verbose_name='Қолданушының курсы'),
        ),
    ]
