# Generated by Django 5.2.3 on 2026-02-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_subject_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lab_link',
        ),
    ]
