# Generated by Django 5.2.3 on 2026-02-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_lesson_lab_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.TextField(verbose_name='URL сілтеме'),
        ),
    ]
