# Generated by Django 5.2.3 on 2026-02-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='params',
            field=models.CharField(choices=[('none', 'Таңдалмаған'), ('Тест', [('quiz', 'Тестілтеу'), ('true-false', 'Ақиқат/жалған')]), ('Сәйкестендіру', [('row', 'Қатар'), ('col', 'Баған')])], default='none', max_length=32, verbose_name='Параметрлер'),
        ),
    ]
