# Generated by Django 5.2.3 on 2026-02-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_task_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessondocs',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Мәтін'),
        ),
    ]
